String element recorder
OpenSees/OpenSees pull request #516
Opened 2021-01-28 01:20 UTC by mhscott

Converting int and double arguments to string for parameters and element recorders

2021-01-28 20:43 UTC, zhuminjie requested changes

2021-01-28 20:43 UTC, zhuminjie commented on SRC/interpreter/OpenSeesOutputCommands.cpp
> +	  argv[i] = new char[128];
You don't have this new char. The return value from OPS_GetStringFromAll is actually a pointer to buffer passed in.

2021-01-28 20:43 UTC, zhuminjie commented on SRC/interpreter/OpenSeesParameterCommands.cpp
> +	char buffer[128];
Same as above

2021-01-28 20:43 UTC, zhuminjie commented on SRC/recorder/ElementRecorder.cpp
> +	    argv = new char*[nargrem];
same as above

2021-02-08 17:33 UTC, fmckenna approved these changes

2021-02-08 17:34 UTC, fmckenna approved these changes

2021-02-08 17:37 UTC, merged